// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvF7WHzq7rXK1F2Q6Fxt4WGK_fzJQcfSU',
    appId: '1:753627592288:web:d6e207f782fe1339e47505',
    messagingSenderId: '753627592288',
    projectId: 'safher-a182b',
    authDomain: 'safher-a182b.firebaseapp.com',
    storageBucket: 'safher-a182b.firebasestorage.app',
    measurementId: 'G-9Y8W78L91Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUa3xvV1YIykkTHeVUQ5fOGEUzp3JCyAI',
    appId: '1:753627592288:android:f00e7897e8c9623ae47505',
    messagingSenderId: '753627592288',
    projectId: 'safher-a182b',
    storageBucket: 'safher-a182b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLkJerGe0ZjUM3ypS0knr_LxEZmcBTm18',
    appId: '1:753627592288:ios:efe505dfea743c31e47505',
    messagingSenderId: '753627592288',
    projectId: 'safher-a182b',
    storageBucket: 'safher-a182b.firebasestorage.app',
    iosBundleId: 'com.example.safher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLkJerGe0ZjUM3ypS0knr_LxEZmcBTm18',
    appId: '1:753627592288:ios:efe505dfea743c31e47505',
    messagingSenderId: '753627592288',
    projectId: 'safher-a182b',
    storageBucket: 'safher-a182b.firebasestorage.app',
    iosBundleId: 'com.example.safher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvF7WHzq7rXK1F2Q6Fxt4WGK_fzJQcfSU',
    appId: '1:753627592288:web:f114915c77d8d4fae47505',
    messagingSenderId: '753627592288',
    projectId: 'safher-a182b',
    authDomain: 'safher-a182b.firebaseapp.com',
    storageBucket: 'safher-a182b.firebasestorage.app',
    measurementId: 'G-TFJQN1P1D9',
  );
}
